name: Docker Image Build, Push to Docker Hub and Deploy in Minikube/k8s

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from Github
    - uses: actions/checkout@v2
    
    - name: Build docker image
      run: docker build . --file Dockerfile --tag ruby-http-server$(date +%s)
    
    - name: Push Docker Image
    - uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: devopsdeepan/ruby-http-server$(date +%s)
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Run playbook
    - uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: deployment.yaml
        directory: ./
